
skillMetadata:
  sections:
    - name: Description
      fields:
        - name: description
          type: label
          label: Find the best hotel for my stay in the US
          value: "false"
